# Generated by Django 5.0.6 on 2024-06-21 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reservahora_tipo_consulta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservahora',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='reservahora',
            name='correo_confirm',
        ),
        migrations.AddField(
            model_name='reservahora',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reservahora',
            name='hora',
            field=models.CharField(default='09:00', max_length=5),
        ),
    ]
