# Generated by Django 5.0.6 on 2024-06-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_reservahora_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservahora',
            name='usuario',
        ),
    ]
