# Generated by Django 5.0.6 on 2024-06-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_reservahora_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservahora',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
