# Generated by Django 5.0.6 on 2024-07-03 19:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reservahora_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservahora',
            unique_together={('user', 'fecha', 'hora')},
        ),
    ]
